version: "3"

services:
  mongo:
    image: mongo
    container_name: mongo
    networks:
      - mongo-compose-network
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_ROOT_USER}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_ROOT_PASSWORD}
    volumes:
      - "./database:/data/db"
    logging:
      driver: none
    expose:
      - "27017"
    restart: unless-stopped

  mongo-express:
    image: mongo-express
    container_name: mongo-express
    networks:
      - mongo-compose-network
    environment:
      - ME_CONFIG_MONGODB_SERVER=mongo
      - ME_CONFIG_OPTIONS_EDITORTHEME=ambiance
      - ME_CONFIG_MONGODB_ENABLE_ADMIN=true
      - ME_CONFIG_MONGODB_ADMINUSERNAME=${MONGO_ROOT_USER}
      - ME_CONFIG_MONGODB_ADMINPASSWORD=${MONGO_ROOT_PASSWORD}
      - ME_CONFIG_BASICAUTH_USERNAME=${MONGOEXPRESS_LOGIN}
      - ME_CONFIG_BASICAUTH_PASSWORD=${MONGOEXPRESS_PASSWORD}
    depends_on:
      - mongo
    ports:
      - 8081:8081
    restart: unless-stopped

  redis:
    image: redis:6.2-alpine
    container_name: redis
    volumes:
      - "./redis:/data"
    expose:
      - "6379"
    restart: unless-stopped

  elasticsearch:
    image: elasticsearch:7.14.1
    container_name: elasticsearch
    volumes:
      - ./elasticsearch:/usr/share/elasticsearch/data
    environment:
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - discovery.type=single-node
    logging:
      driver: none
    expose:
      - "9200"

  newsapp:
    image: newsapp:v0.2
    environment:
      - NODE_ENV=production
    depends_on:
      - mongo
      - redis
      - elasticsearch
    expose:
      - "8080"

  nginx:
    image: owasp/modsecurity-crs:v3.3.2-nginx
    container_name: nginx
    environment:
      - BACKEND=http://newsapp:8080
      - PORT=8082
      - ALLOWED_METHODS=GET HEAD POST PUT PATCH DELETE OPTIONS
    depends_on:
      - newsapp
    expose:
      - "8082"

  varnish:
    image: varnish:6.6-alpine
    container_name: varnish
    environment:
      - CACHE_SIZE=512m
      - VARNISH_MEMORY=100m
    volumes:
      - ./default.vcl:/etc/varnish/default.vcl:ro
    ports:
      - 80:80
    depends_on:
      - nginx

networks:
  mongo-compose-network:
    name: mongo-compose-network
