version: "3"

services:
  mongo:
    image: mongo
    container_name: mongo
    networks:
      - mongo-compose-network
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_ROOT_USER}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_ROOT_PASSWORD}
    volumes:
      - "./database:/data/db"
    ports:
      - 27017:27017
    restart: unless-stopped

  mongo-express:
    image: mongo-express
    container_name: mongo-express
    networks:
      - mongo-compose-network
    environment:
      - ME_CONFIG_MONGODB_SERVER=mongo
      - ME_CONFIG_OPTIONS_EDITORTHEME=ambiance
      - ME_CONFIG_MONGODB_ENABLE_ADMIN=true
      - ME_CONFIG_MONGODB_ADMINUSERNAME=${MONGO_ROOT_USER}
      - ME_CONFIG_MONGODB_ADMINPASSWORD=${MONGO_ROOT_PASSWORD}
      - ME_CONFIG_BASICAUTH_USERNAME=${MONGOEXPRESS_LOGIN}
      - ME_CONFIG_BASICAUTH_PASSWORD=${MONGOEXPRESS_PASSWORD}
    depends_on:
      - mongo
    ports:
      - 8081:8081
    restart: unless-stopped

  redis:
    image: redis:6.2-alpine
    container_name: redis
    volumes:
      - "./redis:/data"
    ports:
      - 6379:6379
    restart: unless-stopped

  newsapp:
    image: newsapp:v0.2
    environment:
      - NODE_ENV=production
    expose:
      - 8080

  nginx:
    image: nginx:1.21-alpine
    container_name: nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - newsapp
    ports:
      - 80:80

networks:
  mongo-compose-network:
    name: mongo-compose-network
